export const UrlCustomers = () => "/customers";
export const UrlTickets = () => "/tickets";
export const UrlCategories = () => "/categories";
export const UrlKnowledge = () => "/knowledge";
export const UrlAgents = () => "/agents";
export const UrlDashboard = () => "/dashboard";
export const UrlAnalytics = () => "/analytics";
export const UrlNotification = () => "/notification";
export const UrlSettings = () => "/settings";
export const UrlNotificationSend = () => "/notification-send";
// export const UrlSettings = () => "/settings";
